### PR TITLE
Port `init-slides.sh` from Bash to Scala

### LINKED ISSUE #7: Consider using a Scala script instead of Bash for `init-slides.sh` example
Looks like the example requires `scala` (old `scala-cli`) anyway. 

So, might as well use it for the [script itself!](https://scala-cli.virtuslab.org/docs/guides/scripting/scripts#self-executable-scala-script)

- Increases the educational value by having a Scala script example.
- Avoids having to basically copy-paste the Scala script into the Bash script.
  - Could probably avoid having the separate `slides.scala` file too. (Simplifies / removes file checking logic)
- Bash scripts can be fragile depending on the environment, with confusing syntax. Scala can be more consistent (and typed!)

What do you think?

### PR DESCRIPTION
**Pull request by spamegg1**
Fixes #7 
- not sure what to do with the comments.
- Removed `xdg-open` part (Windows)
- Can you check `scala run init-taggy.sc` runs OK on Windows? (I don't have access to Windows) It's OK here on Linux.

### CODE REVIEW

**Comment by bjornregnell** [comment]
Many thanks!! Need to go AFK now and tomorrow prepare a talk, but will look at this as soon as I'm back on track with this.

**Comment by bjornregnell** [comment]
BTW: You can bump to the hotfix version 1.0.1 already out (an embarrassing bug :blush: )

**Comment by bjornregnell** [comment]
I'm still swamped by semester start but just had a look and it looks good!

I think the comment should be updated to run the actual file namne ending with `.sc` so that it does not clash with other files in the same dir and the sh ending triggers the scripting feature that does not need main. So update comment to
```
// scala run init-slides.sh 
```
and I'll merge this and later I'll update readme etc to reflect your contrib. Many thanks again!

**Comment by spamegg1** [comment]
> run the actual file namne ending with `.sc`

```scala
// scala run init-slides.sh 
```

Did you mean `scala run init-taggy.sc`?

**Comment by bjornregnell** [comment]
Yes; great; thanks!

**Comment by bjornregnell** [comment]
https://github.com/bjornregnell/taggy/issues/11

**Pull request merged**
